jdbc:
  basic:
    maxOpenPreparedStatements: -1


#    jackson:
#      serialization:
#        write_dates_as_timestamps: false
    data:
      mongodb:
        uri: mongodb://localhost/movieDB
        database: movieDB
        host: localhost
        port: 27017
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  level:
    com.stackroute.movie: DEBUG
